[153] Add the layout children action
eclipse-sirius/sirius-desktop pull request #159
Opened 2023-11-13 14:41 UTC by scosta-obeo

### [153] Add the provider for the layout children action
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/153

### [153] Add the layout children action in the toolbar and the menus
Note that this action does nothing at this commit. The command for the
action is to come in the next commit.

Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/153

2023-12-28 10:17 UTC, lfasani commented
When `Move pinned element` is checked, `Arrange children `behaves like `Arrange All`

2023-12-28 10:39 UTC, lfasani requested changes

2023-12-28 10:39 UTC, lfasani commented on plugins/org.eclipse.sirius.diagram.ui/icons/layoutChildren@2x.png
The icon seems a little blurred compared to the others (All, Selection, Linked Border Nodes)

2023-12-28 10:39 UTC, lfasani commented on plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/menu/DiagramEditorContextMenuProvider.java
> +    private void reorguenizeLayoutMenu(IMenuManager menu) {
reorganize

2023-12-28 17:13 UTC, scosta-obeo commented
For bug when `Move Pinned Elements` is checked, see https://github.com/eclipse-sirius/sirius-desktop/pull/222

2023-12-28 17:14 UTC, scosta-obeo commented on plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/menu/DiagramEditorContextMenuProvider.java
> +    private void reorguenizeLayoutMenu(IMenuManager menu) {
Done

2023-12-29 16:23 UTC, lfasani approved these changes

2023-12-29 16:41 UTC, merged