[173] Merge pin and unpin button in one checkable button
eclipse-sirius/sirius-desktop pull request #213
Opened 2023-12-22 10:00 UTC by scosta-obeo

Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/173

2023-12-28 11:06 UTC, lfasani requested changes

2023-12-29 10:08 UTC, scosta-obeo commented on plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/pinning/PinElementsAction.java
> +     * This method update the action state according selection:
Done

2023-12-29 10:11 UTC, scosta-obeo commented on plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/tools/api/layout/PinHelper.java
> +                return false;
Yes, you're right, it's a postcommit only, so it must return true.

2023-12-29 10:11 UTC, scosta-obeo commented on plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/pinning/PinElementsAction.java
> +        return new PinElementsAction();
Done

2023-12-29 16:21 UTC, lfasani approved these changes

2024-01-02 16:51 UTC, merged