[267] Display invalid representations when viewpoint is not loaded
eclipse-sirius/sirius-desktop pull request #268
Opened 2024-02-14 15:42 UTC by lfasani

It also manages the case when the representation description is not loaded

Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/267

2024-02-14 17:06 UTC, scosta-obeo requested changes

2024-02-14 17:06 UTC, scosta-obeo commented on plugins/org.eclipse.sirius.ui/src/org/eclipse/sirius/ui/tools/internal/views/common/item/RepresentationDescriptionItemImpl.java
>              return representationDescription.getName().compareTo(o.representationDescription.getName());
o.representationDescription can also be null

2024-02-14 17:06 UTC, scosta-obeo commented on plugins/org.eclipse.sirius.ui/src/org/eclipse/sirius/ui/tools/internal/views/common/item/ViewpointItemImpl.java
>              return viewpoint.getName().compareTo(o.viewpoint.getName());
o.viewpoint can be null

2024-02-14 17:06 UTC, scosta-obeo commented on plugins/org.eclipse.sirius.ui/src/org/eclipse/sirius/viewpoint/provider/Messages.java
Copyright 2024

2024-02-15 10:46 UTC, lfasani commented on plugins/org.eclipse.sirius.ui/icons/full/obj16/diagram-type.gif
yes but not in this commit

2024-02-15 15:14 UTC, merged