[205] Fix tests
eclipse-sirius/sirius-desktop pull request #300
Opened 2024-02-25 09:10 UTC by lredor

New actions have been added in Tabbar through issue #205, this changes the expected values in TabBarTest.

Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/205

2024-02-25 09:14 UTC, lredor commented
@scosta-obeo On Sirius IC, there are 4 failures on TabBarTests. These failures are reproductible locally. I have fixed them with this commit. But I've not checked if the changes in the Tabbar are expected or if the tests detected reel regressions.
Can you review this PR and check carefully that the changes detected in tests are expected according to your changes ?

2024-02-26 09:35 UTC, pcdavid approved these changes

2024-02-26 09:36 UTC, pcdavid commented
Approved because I confirm that this fixes the tests for me too, but we still need @scosta-obeo's confirmation that the change is expected.

2024-02-26 10:06 UTC, scosta-obeo requested changes
Ok for `TabBarTest` but there are a lot of unexpected empty files in the commit.

2024-02-26 10:12 UTC, lredor commented
> Ok for `TabBarTest` but there are a lot of unexpected empty files in the commit.

Empty files have been removed.

2024-02-26 10:14 UTC, scosta-obeo approved these changes

2024-02-26 10:15 UTC, merged