[333] Keep routing style with ELK
eclipse-sirius/sirius-desktop pull request #337
Opened 2024-03-26 11:05 UTC by lredor

2024-03-27 13:39 UTC, lredor commented
**Warning:** Before merging, the release notes and the migration participant version must be reviewed. Indeed, these commits have been done too late fore Sirius 7.4.1 (even if the release notes and the migration participant version refere to it).

2024-06-18 12:39 UTC, scosta-obeo requested changes

2024-06-18 12:39 UTC, scosta-obeo commented on plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/diagram/layout/SimpleELKLayoutTest.java
> +                    Edge edge = (Edge) eObject;
You can use Java 17 instanceof:
```suggestion
                if (eObject instanceof Edge edge) {
```

2024-06-20 07:37 UTC, lredor commented on plugins/org.eclipse.sirius.diagram.elk/src/org/eclipse/sirius/diagram/elk/ElkDiagramLayoutConnector.java
> +     * Set the routing style of the <code>edgeContainer</code>, if it it not already set (for example in the VSM
It will be fixed in next version.

2024-06-20 07:39 UTC, lredor commented on plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/diagram/layout/SimpleELKLayoutTest.java
> +                    Edge edge = (Edge) eObject;
It will be fixed in next version.

2024-06-20 07:42 UTC, lredor commented on plugins/org.eclipse.sirius.diagram.elk/src/org/eclipse/sirius/diagram/elk/migration/EmptyJunctionPointsStringValueStyleMigrationParticipant.java
> +        StreamSupport.stream(diagram.getEdges().spliterator(), false).filter(Edge.class::isInstance).forEach(edge -> updateEdge((Edge) edge));
It will be fixed in next version.

2024-06-20 07:48 UTC, lredor reviewed
I have added explicit comment "as review" instead of the comment of the 27th march, ie:
**Warning:** Before merging, the release notes and the migration participant version must be reviewed. Indeed, these commits have been done too late fore Sirius 7.4.1 (even if the release notes and the migration participant version refere to it).

2024-06-20 07:48 UTC, lredor commented on plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile
> +* <span class="label label-success">Added</span> A migration participant, EmptyJunctionPointsStringValueStyleMigrationParticipant,  has been added to fix the GMF edges that contain an empty "junction
The version will be to review just before merge?

2024-06-20 07:48 UTC, lredor commented on plugins/org.eclipse.sirius.diagram.elk/src/org/eclipse/sirius/diagram/elk/migration/EmptyJunctionPointsStringValueStyleMigrationParticipant.java
> +    public static final Version MIGRATION_VERSION = new Version("15.4.3.202406211100"); //$NON-NLS-1$
The version will be to review just before merge?

2024-06-26 14:40 UTC, lredor commented on plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile
> +* <span class="label label-success">Added</span> A migration participant, EmptyJunctionPointsStringValueStyleMigrationParticipant,  has been added to fix the GMF edges that contain an empty "junction
Done

2024-06-26 14:40 UTC, lredor commented on plugins/org.eclipse.sirius.diagram.elk/src/org/eclipse/sirius/diagram/elk/migration/EmptyJunctionPointsStringValueStyleMigrationParticipant.java
> +    public static final Version MIGRATION_VERSION = new Version("15.4.3.202406211100"); //$NON-NLS-1$
Done

2024-06-26 14:59 UTC, scosta-obeo approved these changes

2024-06-26 16:17 UTC, merged