[428] Fix Palette Customization feature
eclipse-sirius/sirius-desktop pull request #429
Opened 2024-07-02 15:45 UTC by GlennPlou

2024-07-02 16:00 UTC, ldelaigue commented
I think we can get rid of the 1st commit, since we want to keep the originally intended behavior as much as possible.
Since it seems that fixing the IDs of the palette elements solve the issue, let's just do that!

2024-07-11 10:55 UTC, scosta-obeo requested changes

2024-07-11 12:06 UTC, GlennPlou commented on plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/palette/PaletteManagerImpl.java
> -                    paletteEntry.setId(nameEntry);
L. 731, setID is made:
```
if (paletteEntry != null) {
                    paletteEntry.setId(ToolManagement.getId(toolDescription));
[...]
```

2024-07-22 13:22 UTC, SteveMonnier approved these changes

2024-07-22 13:34 UTC, merged